name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl --retry 3 --retry-delay 5 --max-time 30 -s https://chat-with-nextgen-coaching.streamlit.app/ > /dev/null
